### PR TITLE
hasher fix str encoding

### PR DESCRIPTION
**Pull request by simonafk**
utf-8 string encoding may cause errors. Avoid the error by switching to
a different encoding.

### CODE REVIEW

**Review by damienrj — APPROVED** [review]
This looks like this should solve the problem we were having

**Comment by jqmp** [comment]
Looks reasonable, but do we need to bump the cache schema version? Some strings will hash to different values with this new encoding, right?

**Comment by simonafk** [comment]
> Looks reasonable, but do we need to bump the cache schema version? Some strings will hash to different values with this new encoding, right?

Makes sense. Updated schema version.

**Review by jqmp — APPROVED** [review]
Looks good, except for the failing test (did you delete the test fixtures?) -- and don't forget the release notes!

**Comment by simonafk** [comment]
> Looks good, except for the failing test (did you delete the test fixtures?) -- and don't forget the release notes!

Ah. I deleted some old test data files, but did not add the new ones. Added them.

**Pull request merged**
